//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Main/Input/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""InputAction"",
            ""id"": ""4a1d0e3d-182a-4e39-9ebf-f983cb2b2af8"",
            ""actions"": [
                {
                    ""name"": ""YAxis"",
                    ""type"": ""Value"",
                    ""id"": ""4890b8db-b21a-4de0-aafa-342d690f8aae"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press,Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""XAxis"",
                    ""type"": ""Value"",
                    ""id"": ""7632e8eb-5da6-4582-adf3-405a2852769c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MainMouseDown"",
                    ""type"": ""Button"",
                    ""id"": ""d7c6daaf-4f46-450b-a8d6-34bb0428f781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainMouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""74b29d33-77cf-46a9-a3ca-06388803f826"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainMouseUp"",
                    ""type"": ""Button"",
                    ""id"": ""af2d99cb-c44a-45ef-b206-bf8c369540fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector - Arrow"",
                    ""id"": ""a590b5d9-0d21-45c4-a863-e9003bbe953d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""10f871c1-9aec-4038-84ef-168cac003d71"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""5e9a210e-7bcb-4034-84ce-00609657d5a1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector - Key"",
                    ""id"": ""a6f744a0-4602-4e86-9e69-9621dd3d658c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""1740f3a2-f267-440f-aae1-2bd28d9318c0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""7a2c3b91-3784-4a4b-bef0-8abed371cca1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis - Arrow"",
                    ""id"": ""539eaaf2-82ba-4559-86bc-73ba9109393d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9f583371-f652-45af-9992-ae89d2a1da1b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3c720ec8-22ef-456a-89c4-2d2b4cb4eff7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis - Key"",
                    ""id"": ""91a4d5e4-976a-4642-bf2b-7d9a5c9e2562"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""aac5143e-1fa8-474b-b0ab-b7f85b04ec1b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6b926483-db3d-4989-97c2-936aaad6bd59"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d2031e77-4189-460f-a194-a49d15c9680d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMouseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb4d5434-b63c-4d29-89d3-52a56c01435b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d748b5a6-6494-4412-9909-6115fc1c2645"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMouseUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InputAction
        m_InputAction = asset.FindActionMap("InputAction", throwIfNotFound: true);
        m_InputAction_YAxis = m_InputAction.FindAction("YAxis", throwIfNotFound: true);
        m_InputAction_XAxis = m_InputAction.FindAction("XAxis", throwIfNotFound: true);
        m_InputAction_MainMouseDown = m_InputAction.FindAction("MainMouseDown", throwIfNotFound: true);
        m_InputAction_MainMouseClick = m_InputAction.FindAction("MainMouseClick", throwIfNotFound: true);
        m_InputAction_MainMouseUp = m_InputAction.FindAction("MainMouseUp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InputAction
    private readonly InputActionMap m_InputAction;
    private IInputActionActions m_InputActionActionsCallbackInterface;
    private readonly InputAction m_InputAction_YAxis;
    private readonly InputAction m_InputAction_XAxis;
    private readonly InputAction m_InputAction_MainMouseDown;
    private readonly InputAction m_InputAction_MainMouseClick;
    private readonly InputAction m_InputAction_MainMouseUp;
    public struct InputActionActions
    {
        private @NewControls m_Wrapper;
        public InputActionActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @YAxis => m_Wrapper.m_InputAction_YAxis;
        public InputAction @XAxis => m_Wrapper.m_InputAction_XAxis;
        public InputAction @MainMouseDown => m_Wrapper.m_InputAction_MainMouseDown;
        public InputAction @MainMouseClick => m_Wrapper.m_InputAction_MainMouseClick;
        public InputAction @MainMouseUp => m_Wrapper.m_InputAction_MainMouseUp;
        public InputActionMap Get() { return m_Wrapper.m_InputAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputActionActions set) { return set.Get(); }
        public void SetCallbacks(IInputActionActions instance)
        {
            if (m_Wrapper.m_InputActionActionsCallbackInterface != null)
            {
                @YAxis.started -= m_Wrapper.m_InputActionActionsCallbackInterface.OnYAxis;
                @YAxis.performed -= m_Wrapper.m_InputActionActionsCallbackInterface.OnYAxis;
                @YAxis.canceled -= m_Wrapper.m_InputActionActionsCallbackInterface.OnYAxis;
                @XAxis.started -= m_Wrapper.m_InputActionActionsCallbackInterface.OnXAxis;
                @XAxis.performed -= m_Wrapper.m_InputActionActionsCallbackInterface.OnXAxis;
                @XAxis.canceled -= m_Wrapper.m_InputActionActionsCallbackInterface.OnXAxis;
                @MainMouseDown.started -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseDown;
                @MainMouseDown.performed -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseDown;
                @MainMouseDown.canceled -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseDown;
                @MainMouseClick.started -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseClick;
                @MainMouseClick.performed -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseClick;
                @MainMouseClick.canceled -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseClick;
                @MainMouseUp.started -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseUp;
                @MainMouseUp.performed -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseUp;
                @MainMouseUp.canceled -= m_Wrapper.m_InputActionActionsCallbackInterface.OnMainMouseUp;
            }
            m_Wrapper.m_InputActionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @YAxis.started += instance.OnYAxis;
                @YAxis.performed += instance.OnYAxis;
                @YAxis.canceled += instance.OnYAxis;
                @XAxis.started += instance.OnXAxis;
                @XAxis.performed += instance.OnXAxis;
                @XAxis.canceled += instance.OnXAxis;
                @MainMouseDown.started += instance.OnMainMouseDown;
                @MainMouseDown.performed += instance.OnMainMouseDown;
                @MainMouseDown.canceled += instance.OnMainMouseDown;
                @MainMouseClick.started += instance.OnMainMouseClick;
                @MainMouseClick.performed += instance.OnMainMouseClick;
                @MainMouseClick.canceled += instance.OnMainMouseClick;
                @MainMouseUp.started += instance.OnMainMouseUp;
                @MainMouseUp.performed += instance.OnMainMouseUp;
                @MainMouseUp.canceled += instance.OnMainMouseUp;
            }
        }
    }
    public InputActionActions @InputAction => new InputActionActions(this);
    public interface IInputActionActions
    {
        void OnYAxis(InputAction.CallbackContext context);
        void OnXAxis(InputAction.CallbackContext context);
        void OnMainMouseDown(InputAction.CallbackContext context);
        void OnMainMouseClick(InputAction.CallbackContext context);
        void OnMainMouseUp(InputAction.CallbackContext context);
    }
}
